//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR17.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Zavtrak { get; set; }
        public string Obed { get; set; }
        public string Ujin { get; set; }
        public int Id_povara { get; set; }
    
        public virtual rabotniki rabotniki { get; set; }
    }
}
